version: '2'
services:
  bot:
    build: .
    image: orca-scan-bot-latest
    env_file:
      - .env
    networks:
      - orcascan
networks:
  orcascan:
    name: orca_scan_default
    external: true